### ISSUE TITLE
[Request] Offline Apple Watch app

### ISSUE THREAD

**Issue by 5rxiq** [rasmuslos/ShelfPlayer#110]
Request for a bare bones app for listening to downloaded podcasts and audiobooks on the Apple Watch. 

Real life use case would be instances where one does not have a phone on them, such as a run.

**Comment by rasmuslos** [comment]
I tried to develop an Apple Watch app for AmpFin a while ago and it's quite tedious todo. Also its [(at least from what I can gather)](https://developer.apple.com/videos/play/wwdc2020/10636/) not even possible to stream or download media files from the ABS server that can be played on the Apple Watch (even with transcoding, you need specific profile, not just codecs). I will close this for now because, if I make an Apple Watch app it will not be in the near future.

**Comment by 5rxiq** [comment]
Thanks for the context!

**Comment by WeisseTeetasse** [comment]
> Another ABS app on iOS just added a Watch app in beta, it definitely seems to work. Would love to see a ShelfPlayer Watch app at some point.

Which? :)

**Comment by kgraefe** [comment]
Plappa has one, I have not tried it, though
