### ISSUE TITLE
ShelfPlayer does not update information from server without clearing cache 

### ISSUE THREAD

**Issue by xcrailer** [rasmuslos/ShelfPlayer#117]
Running ShelfPlayer on the latest iOS, often times ShelfPlayer will not update book progress and other metadata changes from the server without clearing cache.

**Comment by gh0sti** [comment]
Clearing cache is the only option we have right now.

**Comment by xcrailer** [comment]
Are you stating that it is a limitation from AudioBookShelf or that the app needs development to automatically sync with the server without clearing cache?

**Comment by gh0sti** [comment]
> Are you stating that it is a limitation from AudioBookShelf or that the app needs development to automatically sync with the server without clearing cache?

https://github.com/rasmuslos/ShelfPlayer/issues/85

**Comment by xcrailer** [comment]
Thank you for the information. Hopefully this is a feature that is added because it does not automatically update book progress from the server if anything is listened to outside of ShelfPlayer.

**Comment by rasmuslos** [comment]
ShelfPlayer syncs different things at different times.

- Covers are updated once a week or when you press clear cache.
- Progress and bookmarks when you close and open the app (You see a progress spinner and the "Go offline" button) or when you clear the cache
- And Metadata is updated every time you request the item from the server. This does not happen every time you open a for example book page, but e.g. when you refresh the home view. The metadata for the detail pages is taken from the home view. The pull to refresh for the audiobook home view is currently broken but it will be fixed in the next update.

There already is an open issue to sync playback progress more often, for example when finishing playback, so I will close this issue
