### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by saalaataa** [rasmuslos/ShelfPlayer#136]
hello, 
with latest abs 2.13.3, I am not able to login to my server with my credentials. Other ways are working fine, web browser or plappa allow me to log in with credentials provided. When I'm on my ipad, only offline files are available and can't go online. I assume, when I log out, I will be not able to log back in.

**Comment by rasmuslos** [comment]
This started happening after you upgraded to `2.13.3`?

**Comment by saalaataa** [comment]
checked different docker images and last one to be working is 2.12.3. Since 2.13 shelfplayer is not able to login. AFAI can tell, Plappa release patch 1.4.2 addressing this issue.

**Comment by rasmuslos** [comment]
If you didn't use plappa since you downgraded, can you upgrade again and try logging in again. Its important that you don't use plappa to listen to anything before trying this.

**Comment by saalaataa** [comment]
I was using plappa every now and then. Same with shelfplayer. My most often app is still prologue. 

Some additional info: When I upgraded to latest version of ABS and keep shelfplayer logged in, the app is working fine. But when I  force to log out from the app, and try to log back in, I receive error: Login failed, but my ABS logs is showing  no error, but only info [Auth] User "xxx" logged in from ip ...

**Comment by rasmuslos** [comment]
Did you perchance downgrade using an old backup?

**Comment by rasmuslos** [comment]
Sorry for being so harsh earlier, I was mostly mad a plappa. Let me give you a technical explanation of what I think happened:

When you login or authorize (open the app, that's what's happening when you see the loading spinner with the "Go offline" button below it) ShelfPlayer imports your progress (`MediaProgress` entities) from ABS and stores them in a local database.
So going online and logging in fails, because ShelfPlayer is unable to parse said progress entities. But why?

I wasted an hour of my time going to all changes made to ABS since 2.12.3 but wasn't able to find any changes made to either the User or MediaProgress models, as well as the endpoints that use them. That means that none of the underlying structures have changed.

What this means is that this issue is not caused by either ShelfPlayer or ABS. After further investigation I tried using other clients to check if they were the cause of the problem.
I should mention that authorizing and logging in worked fine for me. even when using 2.13.2. This means that the issue cannot be ShelfPlayer or ABS in general (like incompatible data models [meaning that ShelfPlayer expects different things that what the server sends]), because it is working fine for some users.

After playing something in plappa I checked again, a now authorizing was broken for me, too. Checking the logs I found out that the `duration` property of the MediaProgress created by plappa was set to `null`.

This is a problem for ShelfPlayer, because it is statically typed, meaning that `null` (essentially just missing, not present) is not a valid value for the `duration` property. If it is `null` ShelfPlayer will throw an error (login failed).

This is not a problem for ABS-Web because it is written in JavaScript, language without type safety, meaning every property can be whatever (number, string, null, etc.) with fever problems. I am pretty sure this causes some problems in ABS somewhere, but it's probably just `null` being displayed somewhere.

But why does ShelfPlayer expect the duration property to be present? Its a reasonable assumption to make, because the [ABS-API-docs](https://api.audiobookshelf.org/#media-progress) state the following:

| Attribute  | Type | Description |
| --------- | ----- | ------------ |
| duration | Float | The total duration (in seconds) of the media. Will be 0 if the media was marked as finished without the user listening to it. |
| finishedAt | Integer or null | The time (in ms since POSIX epoch) when the media was finished. Will be null if the media has is not finished. |

Note that if something can be null it is explicitly stated.

## But what does all of this mean?
Plappa sets the duration property of the MediaProgress to null when you finish an item. This is not expected behavior. Because ShelfPlayer does not expect this it fails to parse the authorization response and going online, as well as logging in, fail.

So it's pretty annoying to see plappa getting praise for fixing some login issue with 2.13.2, even though there are literally no breaking changes in ABS. There were most likely some internal fixes, but nothing caused by ABS, most likely bug fixes.
I am also pretty mad because I wasted like 1 & 1/2 hours on this, that I could have spend doing literally anything else, only because the developer of plappa could not be bothered to read the API docs and validate their API-request parameters. Here is the code that does exactly that in ShelfPlayer: https://github.com/rasmuslos/ShelfPlayer/blob/4754e59fa66c96be496e32b7a26e8e050445e4f8/ShelfPlayerKit/Sources/SPPlayback/Utility/PlaybackReporter.swift#L136
If I had to guess this is causes by something like `Int(audioPlayer.currentItem?.duration)` which produces `nil` (null in Swift) because the duration is `NaN` (Not a number), because the item is already finished and unloaded by the system.

And #134 is complete unrelated because the user is actually able to login. You can tell because in the screenshot they posted you can see the tab bar, which is only displayed when logged in.

I hope this clear things up!

**Comment by rasmuslos** [comment]
Just to be clear, your issue could be something entirely different, but its quite unlikely.

**Comment by saalaataa** [comment]
Hi @rasmuslos,
don't sweat about it, and thanks for the detailed explanation. Now I understand what you meant referring to the issue caused by plappa, and I am completely on your side with this. 

I ran another test today and created a new user on the latest release of ABS and with new user ShelfPlayer logged in successfully. I will reach to plappa dev, as I don't want to use different accounts on different apps.

**Comment by rasmuslos** [comment]
I already implemented a fix, its pending approval from Apple, it will be available soon. After you install the update you should be able to login again.

You can notify the plappa dev, but at this point the damage is already done, as a client developer you now have to at least consider the possibility that someone has installed plappa, create a malformed MediaProgress and then uninstalled it again, so it invalid objects can still exist, even when a retroactive fix is implemented...

**Comment by rasmuslos** [comment]
There actually is an issue for this already: https://github.com/LeoKlaus/plappa/issues/183
