### ISSUE TITLE
Player bug

### ISSUE THREAD

**Issue by noneme** [rasmuslos/ShelfPlayer#23]
I noticed this bug... most likely this is an error in the framework of the player itself, but maybe not... the point is this: when you launch the application, start playing a previously started book (online), then the progress indicator goes all the way to the edge of the screen, after loading - everything becomes okay.

this is absolutely not critical, but interesting😃 

![image](https://github.com/rasmuslos/ShelfPlayer/assets/5063522/5c6bddf5-59c7-445e-925e-efc92db5b103)

**Comment by rasmuslos** [comment]
This is more or less just a visual bug. The duration is known from the header of the audio file, so it can be loaded without a problem. But the current time is unknown until the audio buffer is big enough. So you are dividing be infinity and infinity back. This causes the progress bar to freak out during the initial buffering. This is not apparent during offline play, because the buffering is way faster. Should be fixed in https://github.com/rasmuslos/ShelfPlayer/commit/81a1164cd3cce133b917442dc6e659c8daf04b44
