### ISSUE TITLE
Feature Request: Custom sleep timer

### ISSUE THREAD

**Issue by PulsarFTW** [rasmuslos/ShelfPlayer#48]
Hey,

An option to enter a custom sleep timer would be nice, I know we can pick nearby and adjust by the minute, but custom options would be great. 

Looking forward to your eventual App Store release!

**Comment by rasmuslos** [comment]
To implement this, what would you want the feature to look like? Change the interval the app adjusts by or having the specifying the amount of seconds left?

**Comment by PulsarFTW** [comment]
I'm not sure the best option from a design point to be fair.

Probably just a "custom" option as the last one on the list and when you click it it'll let you enter any time you want. Or maybe an option to specific one "custom" time and that just gets added to the list? 

A combination of both where it remembers your last custom time would probably be good for most people! 

(Sorry I'm unspecific! - Still refreshing your github daily for official release news)

**Comment by rasmuslos** [comment]
Thanks a lot! I would argue, that most people will not enter seconds, just hours and minutes. And i don't really see an advantage over the current implementation. Just because I am curious, what amount of time would you like to specify?

**Comment by PulsarFTW** [comment]
I don't think anyone would need seconds or even hours and just minutes would be fine. I was trying to find a screenshot of how other apps have done it (prologue, or some I had on adroid years ago) but I don't have any installed right now.

Anyway for me, I typically use 20 minutes and it's not a big issue to press +1 minute a few times.

I was just throwing the suggestion out there in case it was worth adding.

**Comment by rasmuslos** [comment]
I really appreciate any suggestions, they help improve ShelfPlayer. I was just not understanding why you would want this feature to be added, which typically leads to a bad implementation.

This seems to be purely for convenience, not for setting a sleep timer for something enormous like a few hours, as I initially thought. I think a good way to implement this is to remember the last sleep time setting, so if you adjust to 20 minutes using the plus and minus menu options next time there will be an option `20 minutes`. Another idea would be to allow users to set a custom time in the settings, if for example it turns out a lot of users frequently adjust their sleep timer and end up with the wrong remembered value.

**Comment by PulsarFTW** [comment]
Yeah it's absolutely just a convience thing which is why it's not a big problem for me to live without it. I think either of those options would work well although a single custom timer option in the settings would probably lead to less confusion.

Fingers crossed for an appstore release soon!
