### ISSUE TITLE
What is the licensing for this repo?

### ISSUE THREAD

**Issue by slugmuffin** [rasmuslos/ShelfPlayer#5]
There is no license file and no marking on the files other than author tag. Is this planned to be open source with an official license or just assumed copyright of the author?

**Comment by rasmuslos** [comment]
I have answered the same question on my other iOS app, you can find the response [here](https://github.com/rasmuslos/AmpFin/issues/8#issuecomment-1869009789)

But TLDR: I plan on making it open source, probably after the AppStore release, the problem is that the app has been stuck in review for like three weeks now

**Comment by rasmuslos** [comment]
The project is now licenses under MPL v2
