### ISSUE TITLE
[Feature Request] UI similar to Apple Music/Podcasts

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#54]
I was noticing some buttons should when pressed like the home button in the app like music and podcasts returns to the the previous menu and how when dragging the playing UI it should shrink down to the mini playing bar like music and podcasts. 

https://github.com/rasmuslos/ShelfPlayer/assets/4202657/ab7b33f4-fbdf-499c-8b99-0cef3de05bff

**Comment by rasmuslos** [comment]
I tried to add this functionality to the tab bar but as far as I can see this is impossible to do using SwiftUI.
And I absolutely hate the native playback sheets, because as far as I can tell they are not presented modally, these are just views that expand. This is about the worst way you could do this, but I will admit, that the animation looks cool.
But the overhead this would create is not really worth it, but I hope that apple will introduce some features to improve this at the next WWDC.
