### ISSUE TITLE
Occasional Lost Playback Postition

### ISSUE THREAD

**Issue by jonathan-catt** [rasmuslos/ShelfPlayer#77]
Hello,

I am running the App Store version of Shelf Player and experiencing an issue where the current book I am listening to will loose its position and start over from the beginning. It seems to be related to the Online/Offline mode transition. I am using cloudflared to provide public access to the ABS instance running in docker. However, sometimes I open the app while commuting where I do not have connectivity. That said the books I am listening to are all downloaded via Shelf Player. 

Unfortunately as this issue seems to be intermittent not sure what I can provide to help track it down.

App Version: 2.3.5
ABS Version: 2.8.2

**Comment by noneme** [comment]
Oh yeah! I also caught this situation. So we need to observe and describe the situation.

**Comment by rasmuslos** [comment]
I think I noticed this before, too. If this happens, can you just open and close the app (you don't have to be online) and see if this resolves it? This might help to narrow the issue down.

**Comment by gdb19** [comment]
This happens to me frequently too. Pretty much every time I reopen an audiobook in shelfplayer it’s not at the same position as when I last stopped listening. Most times it seems to be a few minutes behind my last listened.

**Comment by gh0sti** [comment]
> This happens to me frequently too. Pretty much every time I reopen an audiobook in shelfplayer it’s not at the same position as when I last stopped listening. Most times it seems to be a few minutes behind my last listened. 

Do you have smart rewind turned on?

**Comment by gdb19** [comment]
No, smart rewind is off. 

It is on a book that I have downloaded in case I need offline access but I'd assume that the reading position should still be synced from Audiobookshelf.

**Comment by rasmuslos** [comment]
Audio sessions are only imported when you open the app after it got terminated. ABS has a pretty unusual design, instead of sending the listening progress with each item you get all sessions when you authorize. So if you listen to an item and then try to resume playback in the app, without reopening it first, it will resume from your last position in the app.

This issue is (I think) meant for another issue were this progress just randomly disappears, but I think https://github.com/rasmuslos/ShelfPlayer/commit/46341295a729bcc7abe06099cb1d1ada4268912c resolved this.

**Comment by gdb19** [comment]
Ok thanks. I didn't appreciate that the app needed to be reopened to sync. I'll close it down in future. Cheers

**Comment by rasmuslos** [comment]
I am pretty sure that https://github.com/rasmuslos/ShelfPlayer/commit/46341295a729bcc7abe06099cb1d1ada4268912c actually resolved this
